### ISSUE TITLE
Enforce certain props to use css variables

### ISSUE THREAD

**Issue by satazor** [moxystudio/stylelint-config-moxy#11]
color, background-color and other stuff should use variables.

See: https://github.com/AndyOGo/stylelint-declaration-strict-value

**Comment by marialuisarosas** [comment]
Basta utilizar a seguinte estrutura de código, sendo que o nome da variável deve sempre começar por --:

:root {
  --main-background-color: coral; 
  --main-color: white;
  --main-padding: 15px; 
}

#div-test {
  background-color: var(--main-bg-color); 
  color: var(--main-color);
  padding: var(--main-padding);
}

**Comment by satazor** [comment]
Hello @marialuisarosas. Let’s keep chatting in English so that non-Portuguese people can understand. We know that CSS variables must start with a dash. This issue is about enforcing it by using a stylelint plugin (which is mentioned above).

The task is basically enabling that plugin, configure it correctly, and add some tests.

**Comment by nlfonseca** [comment]
We suggest having the following props with variables:

```
/* ==========================================================================
   Colors
   ========================================================================== */

:root {
   --color-white: #fff;
   --color-black: #000;
   --color-transparent: color(#fff a(0%));
}

/* ==========================================================================
   Typography
   ========================================================================== */

:root {
    --font-family: "Arial", "Helvetica", sans-serif;

    --font-weight-regular: 400;
    --font-weight-medium: 500;
}

/* ==========================================================================
   Z-index
   ========================================================================== */

:root {
    --z-index-base: 0;
    --z-index-header: 2;
    --z-index-modal: 3;
}
